language: haskell
env:
- GHCVER=7.8.4
- GHCVER=7.10.2
- GHCVER=head
matrix:
  allow_failures:
  - env: GHCVER=head
before_install:
- |
  if [ $GHCVER = `ghc --numeric-version` ]; then
    travis/cabal-apt-install --enable-tests $MODE
    export CABAL=cabal
  else
    travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    travis_retry sudo apt-get update
    travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER happy
    export CABAL=cabal-1.22
    export PATH=/opt/ghc/$GHCVER/bin:$PATH
  fi
- $CABAL update
- |
  if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.2" ]; then
    $CABAL install happy alex
    export PATH=$HOME/.cabal/bin:$PATH
  fi
install:
- $CABAL install --dependencies-only --enable-tests
- $CABAL configure -flib-Werror --enable-tests $MODE
script:
- ghc --numeric-version
- $CABAL check
- $CABAL build
- $CABAL test --show-details=always
deploy:
  provider: hackage
  username: AlexanderThiemann
  skip_cleanup: true
  on:
    condition: "$GHCVER = 7.8.4"
    tags: true
  password:
    secure: aeBH/I8w2COXJ+QeRdTcelEveteWNSOg6ir4uTuh1aFxquXpkfnsbmK8fexjnvZnSOJMaAcjadorGxPBtQfy1dycTnDtYrX2qhf/vXCVEsMy3faMzadfMLg9iXaMvwUiaBeOT/NlG8T4BggQlQdEPwZUG/gWduYqLwM7ykHPmmkqQWX+8vDw5Sya+oS2Qe9InFPejTNjYX8ZYVJdII0kpYt5mYu9PvbYbDO+2CE9w+YW5D0nJ6VgWHPsdWQiqAS9/3uCPdPC0fzCjdCrCgA5ECxdATuIOFl3jZnQcV3cNZEWpsbxt4OBstj8zPmyc3SrFr0lxFf9oSYqVo4o6zDEO7Y0zBcc3i+a2hMmDVhvUhTaWCop3cLtuNTLHo96usAtALfG/XL0QPhBVhG8OL8aBu40px1As/tINvwThHZxyJ7t1GVgtTb9ZoKd9VQna5avlLevHGUyM8vYhZieTZO4drtaGZlXJsuJ4dzFt3evLbqMgm7piM1w0ZRsJfaJrQasqKDg/p9aPu6b0itCjIR8oZl4JRs8E5HutDeRrkY/Y3lw3F57MpSHvIwtc102QvWTqB+YeIMuVd9AEMANV9ZXO8V9PN8DXeCmFuN1Ck21UI0y0gz4T52NOInLHb0tizgIvjK8afL28PHWRyv+61T09uhQOGBSvm81+xn34K4Noc0=
